### ISSUE TITLE
请问prepare_data函数在哪里？

### ISSUE THREAD

**Issue by igeng** [YushengZhao/mmdet_attacker_fusion#1]
您好，我在尝试运行您的代码文件时，发现mmdet.apis中并没有prepare_data函数，请问这个函数在哪里？谢谢您！
from mmdet.apis import prepare_data  # 检测器

**Comment by YushengZhao** [comment]
我们修改了mmdetection，你可以使用我们修改后的代码。这些代码现在已经上传了。

**Comment by YushengZhao** [comment]
你也可以参考https://github.com/FenHua/DetDak
