### ISSUE TITLE
prepare_data

### ISSUE THREAD

**Issue by zhangchang725** [YushengZhao/mmdet_attacker_fusion#2]
This code need a package named prepare_data  ,can author  update it？

**Comment by YushengZhao** [comment]
prepare_data is not a package, it's a function at mmdetection/mmdet/apis/inference.py Line 78

**Comment by zhangchang725** [comment]
您好，非常感谢收到您的来信。
我已经按照您说的已经修改了，但我在运行代码的时候发现了一个bug，并且这个部分我也不太懂。能再询问一下您吗？
下图中，result是一个列表，可是您result[i][j,4]这儿，这是什么意思啊，[j：4]我知道是切片，但是您不只一个地方用到了逗号，报错中会提示list indices must be integers or slices,not tuple.
希望得到您的回复。



---Original---

**Comment by YushengZhao** [comment]
我没看到图啊

**Comment by zhangchang725** [comment]
刚刚又发了一下，您看收到了吗



---Original---

**Comment by YushengZhao** [comment]
> 刚刚又发了一下，您看收到了吗
> […](#)
> ---Original--- From: "YushengZhao"<notifications@github.com&gt; Date: Tue, Nov 10, 2020 16:06 PM To: "YushengZhao/mmdet_attacker_fusion"<mmdet_attacker_fusion@noreply.github.com&gt;; Cc: "zhangchang725"<1806833988@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [YushengZhao/mmdet_attacker_fusion] prepare_data (#2) 我没看到图啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没。。。

**Comment by zhangchang725** [comment]
那能不能加个微信呢，很想复现这个项目。但已经调了一天多了，还是没有调成功。
请教您一下。
我的微信：zc1806833988



---Original---
